# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  circle1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install
          command: |
              sudo apt update && sudo apt install git aria2 rsync neofetch nano tmux build-essential screen xclip silversearch* -y
              wget https://raw.githubusercontent.com/Sushrut1101/Ubuntu-Tmate/master/tmate && sudo apt-get update && sudo apt-get install tmate -y && sudo bash tmate
workflows:
  say-hello-workflow:
    jobs:
      - circle1
